"""Write the commit and build date into `version.py` before packaging.

Run from `build.bat` and from the release workflow. A frozen app has no git
repository to ask at runtime, so the answer to "which build is this" has to be
baked in. Restores the file afterwards with `--restore`, so a build never
leaves the working tree dirty.

It also refuses to stamp anything when the places that declare the version
disagree. That is the half worth having. Until this was ported in,
`installer.iss` was the only place WeekNumber's version existed at all: it
said 1.0.0 from the first commit to the last, through five releases' worth of
changes, because there was nothing to compare it to and nothing that would
have noticed.

Ported from ShooApp, which took it from Service Officer.
"""

from __future__ import annotations

import datetime
import os
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent
TARGET = ROOT / "version.py"
BACKUP = TARGET.with_suffix(".py.orig")

#: The build counter. Not committed: it counts builds *on this machine*, which
#: is what "which build is this" means while iterating. The commit is what
#: identifies the code absolutely.
COUNTER = ROOT / ".build-number"

#: The version the *installer* stamps on itself, written here because the .iss
#: cannot work it out: the build number is counted at build time and
#: `version.py` is restored before ISCC runs. Without it the installer would
#: say "1.2.0 will be upgraded to 1.2.0" — true about the release and useless
#: about the two things that actually differ.
FOR_INSTALLER = ROOT / "installer-version.txt"

#: The Win32 version resource, handed to PyInstaller as `--version-file`.
#: Written here rather than kept in the tree so it cannot disagree with
#: `version.py`: it is generated from the same numbers in the same run.
VERSION_RESOURCE = ROOT / "version_info.txt"

#: Who the exe says it is, in the fields the Properties tab shows. The same
#: publisher `installer.iss` puts in Programs and Features.
PUBLISHER = "ismailorhan"
DESCRIPTION = "WeekNumber - the ISO week number in the system tray"


def version_resource(version: str, build: int) -> str:
    """The `--version-file` PyInstaller stamps into the exe.

    Without one the exe has no version resource at all: the Details tab of
    its Properties shows nothing, and `Get-Process WeekNumber` reports an empty
    FileVersion. The only place that then knows which build is installed is
    the Uninstall key the *installer* wrote — which answers "what was
    installed", not "what is this exe", and the two differ exactly when
    something went wrong with an upgrade.

    Two shapes of the same number, because Windows asks for both: a 4-tuple
    for the fixed part, which is what sorts and compares, and a string for
    the part people read. The fourth number is the build counter, 0 on a
    release, and it is what tells two exes off one release apart.
    """
    try:
        major, minor, patch = (int(part) for part in version.split("."))
    except ValueError:
        # PyInstaller eval's this file as Python. Failing here names the
        # version that was wrong; failing there reports a tuple with a string
        # in it, from a file nobody wrote by hand.
        raise ValueError(f"the version must be three numbers, not {version!r}")

    shown = version + (f".{build}" if build else "")
    numbers = f"({major}, {minor}, {patch}, {build})"
    return f"""# Generated by stamp_version.py -- do not edit, and do not commit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={numbers},
    prodvers={numbers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{PUBLISHER}'),
         StringStruct('FileDescription', '{DESCRIPTION}'),
         StringStruct('FileVersion', '{shown}'),
         StringStruct('InternalName', 'WeekNumber'),
         StringStruct('OriginalFilename', 'WeekNumber.exe'),
         StringStruct('ProductName', 'WeekNumber'),
         StringStruct('ProductVersion', '{shown}')])
    ]),
    # 1033 is en-US and 1200 is Unicode -- which is what '040904B0' above
    # spells out in hex, and the two have to agree.
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def git(*args) -> str:
    try:
        out = subprocess.run(("git",) + args, capture_output=True, text=True,
                             timeout=15, cwd=ROOT)
        return out.stdout.strip() if out.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def next_build(version: str, release: bool) -> int:
    """The build number for this build.

    Counts builds, not commits: several builds can come off one commit while
    something is being tried, and "which build is this" has to tell them
    apart. Restarts at 1 when the release version changes, so 1.3.0's builds
    do not carry on from 1.2.0's. A tagged release build is 0 — a release has
    no fourth part.
    """
    if release:
        return 0
    previous_version, count = "", 0
    if COUNTER.exists():
        try:
            previous_version, _, text = COUNTER.read_text(
                encoding="utf-8").strip().partition(" ")
            count = int(text or 0)
        except (OSError, ValueError):
            previous_version, count = "", 0
    count = count + 1 if previous_version == version else 1
    try:
        COUNTER.write_text(f"{version} {count}\n", encoding="utf-8")
    except OSError:
        pass                       # a read-only checkout still builds
    return count


def stamp(version: str, release: bool) -> tuple[str, str, int]:
    commit = git("rev-parse", "--short", "HEAD") or "unknown"
    # A build from an edited tree is not the commit it claims to be, and that
    # is exactly the confusion this stamp exists to prevent.
    if git("status", "--porcelain"):
        commit += "-dirty"
    built = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    return commit, built, next_build(version, release)


def declared_versions() -> dict[str, str]:
    """The version as each place spells it.

    Three copies exist — `version.py`, `installer.iss`, and the git tag
    on a release build. Comparing them is the point: each one alone is a
    number somebody typed.
    """
    found: dict[str, str] = {}

    match = re.search(r'^VERSION = "(.*)"$', TARGET.read_text(encoding="utf-8"),
                      flags=re.M)
    if match:
        found["version.py"] = match.group(1)

    iss = ROOT / "installer.iss"
    if iss.exists():
        # `MyRelease`, not `MyAppVersion`. The latter is computed — read from
        # the file this script leaves, so the installer can show a build
        # number — and a regex looking for a literal that is no longer there
        # matches nothing and compares two copies while claiming three.
        match = re.search(r'^#define MyRelease\s+"(.*)"$',
                          iss.read_text(encoding="utf-8"), flags=re.M)
        if match:
            found["installer.iss"] = match.group(1)

    # On a tag build the workflow tells us the tag; locally there may be none.
    ref = os.environ.get("GITHUB_REF_NAME", "")
    if re.fullmatch(r"v\d+\.\d+\.\d+", ref):
        found["git tag"] = ref[1:]
    return found


def main() -> int:
    if "--restore" in sys.argv:
        if BACKUP.exists():
            shutil.move(str(BACKUP), str(TARGET))
            print("version.py restored")
        return 0

    declared = declared_versions()
    if len(set(declared.values())) > 1:
        print("[ERROR] the version is spelled differently in each place:")
        for where, value in declared.items():
            print(f"          {where}: {value}")
        return 1

    version = declared.get("version.py", "0.0.0")
    # A build from a version tag is the release itself; anything else is an
    # internal build and gets a build number.
    release = "git tag" in declared
    commit, built, build = stamp(version, release)

    text = TARGET.read_text(encoding="utf-8")
    shutil.copy2(str(TARGET), str(BACKUP))
    text = re.sub(r'^COMMIT = ".*"$', f'COMMIT = "{commit}"', text,
                  count=1, flags=re.M)
    text = re.sub(r'^BUILT = ".*"$', f'BUILT = "{built}"', text,
                  count=1, flags=re.M)
    text = re.sub(r"^BUILD = \d+$", f"BUILD = {build}", text, count=1, flags=re.M)
    TARGET.write_text(text, encoding="utf-8")

    shown = version + (f".{build}" if build else "")
    # Left in place by --restore on purpose: ISCC runs after the build, by
    # which time version.py is back to what it was in git.
    FOR_INSTALLER.write_text(shown + "\n", encoding="utf-8")
    VERSION_RESOURCE.write_text(version_resource(version, build),
                                encoding="utf-8")
    print(f"stamped {shown} commit={commit} built={built}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
